# Generated by Django 3.2.13 on 2023-03-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0003_auto_20211203_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2048)),
                ('instructions', models.CharField(default='Sort the elements on the right to their conterparts on the left.', max_length=2048)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
        migrations.CreateModel(
            name='SortingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed', models.CharField(max_length=512)),
                ('dragable', models.CharField(max_length=512)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one_to_one.onetoone')),
            ],
        ),
    ]
