# Generated by Django 3.2.13 on 2023-03-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortingpair',
            old_name='dragable',
            new_name='draggable',
        ),
        migrations.AlterField(
            model_name='onetoone',
            name='instructions',
            field=models.CharField(default='Sort the elements on the right to their counterparts on the left.', max_length=2048),
        ),
    ]
