# Generated by Django 5.2.9 on 2026-02-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20221115_1032'),
        ('slide', '0010_auto_20250818_0913'),
        ('task', '0004_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slide',
            field=models.ManyToManyField(blank=True, to='slide.slide'),
        ),
        migrations.AlterField(
            model_name='course',
            name='task',
            field=models.ManyToManyField(blank=True, to='task.task'),
        ),
    ]
