# Generated by Django 3.2 on 2021-09-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_organ', models.BooleanField(help_text='Is this an organ tag?')),
                ('is_system', models.BooleanField(help_text='Is this a system tag?')),
            ],
        ),
    ]
