# Generated by Django 3.2 on 2021-09-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='is_organ',
            field=models.BooleanField(default=False, help_text='Is this an organ tag?'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Is this a system tag?'),
        ),
    ]
