# Generated by Django 3.2.10 on 2022-02-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20210922_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_stain',
            field=models.BooleanField(default=False, help_text='Is this a stain tag?'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_system',
        ),
    ]
