# Generated by Django 3.2 on 2021-09-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0004_slide_tags'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='annotated_slide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='slide.annotatedslide'),
            preserve_default=False,
        ),
    ]
