# Generated by Django 3.2 on 2021-12-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20210922_1104'),
        ('task', '0002_task_annotated_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pathology',
            field=models.BooleanField(default=False, help_text='Is the task about pathology or not (general histology)'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
