# Generated by Django 5.2.9 on 2026-02-09 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0003_auto_20211203_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='Click on the letter to find the annotation.', max_length=2048)),
                ('instructions', models.CharField(default='Match the letters to the correct labels by dragging the labels up and down.', max_length=2048)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
