# Generated by Django 3.2 on 2025-09-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250818_0913'),
        ('user', '0002_auto_20250828_0952'),
    ]

    operations = [
    ]
