# Generated by Django 3.2 on 2021-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('slide', '0003_slide_pathology'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
