# Generated by Django 3.2.13 on 2022-12-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0006_slide_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('text', models.CharField(max_length=256)),
                ('annotated_slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slide.annotatedslide')),
            ],
        ),
    ]
