# Generated by Django 3.2.13 on 2024-01-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0008_auto_20230202_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_string', models.TextField(help_text='The annotation in W3C format (JSON) stored as a string')),
                ('annotated_slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slide.annotatedslide')),
            ],
        ),
    ]
