# Generated by Django 3.2 on 2025-08-18 09:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slide', '0009_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=255)),
                ('finished', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('date_uploaded', models.DateTimeField(default=datetime.datetime.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pointer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pointer',
            name='annotated_slide',
        ),
        migrations.AddField(
            model_name='slide',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='slide',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slide',
            name='pathology',
            field=models.BooleanField(default=False, help_text='Does the slide show pathology or histology'),
        ),
        migrations.DeleteModel(
            name='BoundingBox',
        ),
        migrations.DeleteModel(
            name='Pointer',
        ),
    ]
