# Generated by Django 5.2.9 on 2026-07-13 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0010_auto_20250818_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
