# Generated by Django 3.2 on 2021-09-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choice', '0002_alter_multiplechoice_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='slide',
            new_name='annotated_slide',
        ),
    ]
