# Generated by Django 3.2 on 2021-09-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0002_annotatedslide_pointer'),
        ('multiple_choice', '0003_rename_slide_multiplechoice_annotated_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='annotated_slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slide.annotatedslide'),
        ),
    ]
