# Generated by Django 3.2 on 2021-09-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choice', '0004_alter_multiplechoice_annotated_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='annotated_slide',
        ),
    ]
