# Generated by Django 3.2.10 on 2022-03-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choice', '0005_remove_multiplechoice_annotated_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoice',
            name='instructions',
            field=models.CharField(default='Choose the correct answer(s)', max_length=2048),
        ),
    ]
