# Generated by Django 3.2.16 on 2023-01-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0006_slide_long_description'),
        ('multiple_choice', '0006_multiplechoice_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomMCChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('correct', models.BooleanField()),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slide.slide')),
            ],
        ),
    ]
