# Generated by Django 5.2.9 on 2026-02-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choice', '0007_randommcchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoice',
            name='explanation',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
